[main]
font=JetBrainsMono Nerd Font:size=11
prompt="  "
icon-theme=Papirus-Dark
width=35
horizontal-pad=30
vertical-pad=20
inner-pad=10
anchor=center
lines=10

[colors]
# Fond gris-bleu très profond (moins sec que le noir pur)
background=24283bff
# Texte blanc cassé (moins agressif que le blanc pur)
text=c0caf5ff
# Couleur de recherche : Bleu Cyan doux
match=7dcfffff
# Sélection : Un gris-bleu moyen
selection=3b4261ff
# Texte sélectionné : Lavande clair
selection-text=bb9af7ff
# Bordure : Bleu acier discret
border=7dcfff77

[border]
width=2
radius=12